#ifndef CTR_NATIVE_NAMESPACE_SELECTPROFILE_H
#define CTR_NATIVE_NAMESPACE_SELECTPROFILE_H

enum SelectProfileMode
{
	SELECT_PROFILE_ACTION_MASK = 0x0f,
	SELECT_PROFILE_ACTION_LOAD = 0x00,
	SELECT_PROFILE_ACTION_SAVE = 0x01,
	SELECT_PROFILE_ACTION_DELETE = 0x02,

	SELECT_PROFILE_SCREEN_MASK = 0xf0,
	SELECT_PROFILE_SCREEN_ADV_NEW = 0x00,
	SELECT_PROFILE_SCREEN_ADV_LOAD = 0x10,
	SELECT_PROFILE_SCREEN_GREEN_LOAD_SAVE = 0x20,
	SELECT_PROFILE_SCREEN_GHOST = 0x30,
	SELECT_PROFILE_SCREEN_SLOT_SELECTED = 0x40,

	SELECT_PROFILE_MODE_ADV_SAVE = SELECT_PROFILE_SCREEN_ADV_NEW | SELECT_PROFILE_ACTION_SAVE,
	SELECT_PROFILE_MODE_GHOST_SAVE = SELECT_PROFILE_SCREEN_GHOST | SELECT_PROFILE_ACTION_SAVE,
	SELECT_PROFILE_MODE_SLOT_SAVE = SELECT_PROFILE_SCREEN_SLOT_SELECTED | SELECT_PROFILE_ACTION_SAVE,
};

enum SelectProfileConstants
{
	SELECT_PROFILE_DRAW_STYLE_GREEN = 0x10,
	SELECT_PROFILE_INPUT_NAV_CONFIRM = 0x4007f,

	SELECT_PROFILE_UI_CENTER_X = 0x100,
	SELECT_PROFILE_UI_CENTER_Y = 0x6c,
	SELECT_PROFILE_UI_DEPTH = 0x100,
	SELECT_PROFILE_UI_SCALE = 0x100,

	SELECT_PROFILE_ADV_SAVE_BYTES = 0x1680,
	SELECT_PROFILE_GHOST_SAVE_BYTES = 0x3e00,
	SELECT_PROFILE_GHOST_SLOT_COUNT = 7,
	SELECT_PROFILE_DEFAULT_GHOST_TIME = 0x8ca00,
};

CTR_STATIC_ASSERT(SELECT_PROFILE_ACTION_LOAD == 0);
CTR_STATIC_ASSERT(SELECT_PROFILE_ACTION_SAVE == 1);
CTR_STATIC_ASSERT(SELECT_PROFILE_ACTION_DELETE == 2);
CTR_STATIC_ASSERT(SELECT_PROFILE_DRAW_STYLE_GREEN == 0x10);
CTR_STATIC_ASSERT(SELECT_PROFILE_INPUT_NAV_CONFIRM == 0x4007f);
CTR_STATIC_ASSERT(SELECT_PROFILE_UI_CENTER_X == 0x100);
CTR_STATIC_ASSERT(SELECT_PROFILE_UI_CENTER_Y == 0x6c);
CTR_STATIC_ASSERT(SELECT_PROFILE_UI_DEPTH == 0x100);
CTR_STATIC_ASSERT(SELECT_PROFILE_UI_SCALE == 0x100);
CTR_STATIC_ASSERT(SELECT_PROFILE_ADV_SAVE_BYTES == 0x1680);
CTR_STATIC_ASSERT(SELECT_PROFILE_GHOST_SAVE_BYTES == 0x3e00);
CTR_STATIC_ASSERT(SELECT_PROFILE_GHOST_SLOT_COUNT == 7);
CTR_STATIC_ASSERT(SELECT_PROFILE_DEFAULT_GHOST_TIME == 0x8ca00);

struct SelectProfileLoadSaveIcon
{
	struct Instance *inst;
	SVec3 rot;
	s16 padding;
};

struct SelectProfileLoadSaveObj
{
	struct Thread *thread;
	struct SelectProfileLoadSaveIcon *icons;
};

CTR_STATIC_ASSERT(sizeof(struct SelectProfileLoadSaveIcon) == 0xc);
CTR_STATIC_ASSERT(sizeof(struct SelectProfileLoadSaveObj) == 0x8);

#endif
